error fixes
Error: removed warnings
Label: "asserts" no longer defined
SyntaxError: fixed bug introduced by making any_error.text allocated
Z80Assembler, outputfile: united addError() and setError()